@startuml
interface FabricaArtefatos {
  +criarComprovanteFiscal(): ComprovanteFiscal
  +criarPagamento(): Pagamento
  +criarTermoPrivacidade(): TermoPrivacidade
}
class FabricaBrasil
class FabricaMexico
FabricaArtefatos <|.. FabricaBrasil
FabricaArtefatos <|.. FabricaMexico

interface ComprovanteFiscal {
  +descrever(valor: double): String
}
interface Pagamento {
  +descrever(valor: double): String
}
interface TermoPrivacidade {
  +descrever(): String
}

class NFSe
class CFDI
ComprovanteFiscal <|.. NFSe
ComprovanteFiscal <|.. CFDI

class PagamentoPix
class PagamentoSPEI
Pagamento <|.. PagamentoPix
Pagamento <|.. PagamentoSPEI

class TermoLGPD
class TermoLFPDPPP
TermoPrivacidade <|.. TermoLGPD
TermoPrivacidade <|.. TermoLFPDPPP

class Assinatura {
  -cliente: String
  -valor: double
  -comprovante: ComprovanteFiscal
  -pagamento: Pagamento
  -termo: TermoPrivacidade
  +Assinatura(cliente: String, valor: double, fabrica: FabricaArtefatos)
  +ativar(): void
}
Assinatura o--> FabricaArtefatos : recebe no construtor
Assinatura --> ComprovanteFiscal
Assinatura --> Pagamento
Assinatura --> TermoPrivacidade

FabricaBrasil ..> NFSe : <<create>>
FabricaBrasil ..> PagamentoPix : <<create>>
FabricaBrasil ..> TermoLGPD : <<create>>
FabricaMexico ..> CFDI : <<create>>
FabricaMexico ..> PagamentoSPEI : <<create>>
FabricaMexico ..> TermoLFPDPPP : <<create>>
@enduml